version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ic_project
    entrypoint: python /apps/run.py
    env_file:
      - ./.env
    environment:
      - model_cfg_pth=apps/machine_learning/configs/models.yaml
      - data_cfg_pth=apps/machine_learning/configs/data.yaml
    volumes:
      - ".:/apps"
    ports:
      - "${LOCAL_HOST_PORT}:${DOCKER_HOST_PORT}"
    stdin_open: true
    tty: true
