version: '3'


services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ic_project
    entrypoint: python /apps/run.py
    env_file:
      - ./.env
    volumes:
      - ".:/apps"
    ports:
      - "8008:${API_PORT}"